package kelimeoyunuödevi;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author malco
 */
public class Arayüz extends javax.swing.JFrame {

    /**
     * Creates new form Arayüz
     */
    static String adı_soyadı;
    public Arayüz() {
        this.setBounds(700,350,500,400);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sorucevapekleme = new javax.swing.JButton();
        oyunuoyna = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ad_soyad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kelime Oyunu");

        sorucevapekleme.setText("Soru-Cevap Ekleme");
        sorucevapekleme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sorucevapeklemeMouseClicked(evt);
            }
        });
        sorucevapekleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorucevapeklemeActionPerformed(evt);
            }
        });

        oyunuoyna.setText("Oyunu Oyna");
        oyunuoyna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyunuoynaActionPerformed(evt);
            }
        });

        jLabel1.setText("Kelime Oyununa Hoşgeldiniz !");

        ad_soyad.setText("Adınızı Giriniz");
        ad_soyad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ad_soyad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ad_soyadMousePressed(evt);
            }
        });
        ad_soyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_soyadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(sorucevapekleme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(oyunuoyna)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(ad_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sorucevapekleme)
                    .addComponent(oyunuoyna))
                .addGap(52, 52, 52)
                .addComponent(ad_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sorucevapeklemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sorucevapeklemeActionPerformed
    this.setVisible(false);
    new scekleme4().setVisible(true);
    }//GEN-LAST:event_sorucevapeklemeActionPerformed

    private void oyunuoynaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyunuoynaActionPerformed
    this.setVisible(false);
    new oyunuoyna().setVisible(true);
    adı_soyadı=ad_soyad.getText();
    }//GEN-LAST:event_oyunuoynaActionPerformed

    private void sorucevapeklemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sorucevapeklemeMouseClicked
    
    }//GEN-LAST:event_sorucevapeklemeMouseClicked

    private void ad_soyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_soyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad_soyadActionPerformed

    private void ad_soyadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ad_soyadMousePressed
        ad_soyad.setText("");
    }//GEN-LAST:event_ad_soyadMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arayüz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arayüz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_soyad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton oyunuoyna;
    private javax.swing.JButton sorucevapekleme;
    // End of variables declaration//GEN-END:variables
}
