package kelimeoyunuödevi;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author malco
 */
public class scekleme4 extends javax.swing.JFrame {

    /**
     * Creates new form ekleme
     */
    public scekleme4() {
        initComponents();
        this.setBounds(700,350,500,400);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        geri = new javax.swing.JButton();
        soru = new javax.swing.JTextField();
        soruyuekle = new javax.swing.JButton();
        cevap = new javax.swing.JTextField();
        cevabıekle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        geri1 = new javax.swing.JButton();

        geri.setText("Geri");
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soru-Cevap Ekleme");

        soru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soruActionPerformed(evt);
            }
        });

        soruyuekle.setText("Soruyu Ekle");
        soruyuekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soruyuekleActionPerformed(evt);
            }
        });

        cevap.setEnabled(false);

        cevabıekle.setEnabled(false);
        cevabıekle.setText("Cevabı Ekle");
        cevabıekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevabıekleActionPerformed(evt);
            }
        });

        jLabel1.setText("Öncelikle Soruyu Ardından Cevabı Ekleyiniz");

        geri1.setText("Geri");
        geri1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cevabıekle)
                            .addComponent(soruyuekle)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(cevap, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(soru, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(geri1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(geri1)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(soru, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(soruyuekle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cevap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cevabıekle)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
        this.setVisible(false);
        new Arayüz().setVisible(true);
    }//GEN-LAST:event_geriActionPerformed

    private void geri1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri1ActionPerformed
        this.setVisible(false);
        new Arayüz().setVisible(true);
    }//GEN-LAST:event_geri1ActionPerformed

    private void soruyuekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soruyuekleActionPerformed
        
        cevap.setEnabled(true);
        cevabıekle.setEnabled(true);
        soruyuekle.setEnabled(false);
       
    }//GEN-LAST:event_soruyuekleActionPerformed

    private void soruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soruActionPerformed
       
        
        
        
        
        
    }//GEN-LAST:event_soruActionPerformed

    private void cevabıekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevabıekleActionPerformed

        soruyuekle.setEnabled(true);
        cevabıekle.setEnabled(false);
        cevapyazma nesne=new cevapyazma();
        soruyazma nesne2=new soruyazma();
        int a;
        a=cevap.getText().length();
        String cevap1=cevap.getText();
        String soru1=soru.getText();
        switch(a){
            case 4:
                nesne2.dac(1);
                nesne2.dyaz(soru1);
                nesne2.dkapat();
                nesne.dac(1);
                nesne.dyaz(cevap1);
                nesne.dkapat();
                break;
            case 5:
                nesne2.dac(2);
                nesne2.dyaz(soru1);
                nesne2.dkapat();
                nesne.dac(2);
                nesne.dyaz(cevap1);
                nesne.dkapat();
                break;
            case 6:
                nesne2.dac(3);
                nesne2.dyaz(soru1);
                nesne2.dkapat();
                nesne.dac(3);
                nesne.dyaz(cevap1);
                nesne.dkapat();
                break;
            case 7:
                nesne2.dac(4);
                nesne2.dyaz(soru1);
                nesne2.dkapat();
                nesne.dac(4);
                nesne.dyaz(cevap1);
                nesne.dkapat();
                break;
            case 8:
                nesne2.dac(5);
                nesne2.dyaz(soru1);
                nesne2.dkapat();
                nesne.dac(5);
                nesne.dyaz(cevap1);
                nesne.dkapat();
                break;
            case 9:
                nesne2.dac(6);
                nesne2.dyaz(soru1);
                nesne2.dkapat();
                nesne.dac(6);
                nesne.dyaz(cevap1);
                nesne.dkapat();
                break;
            case 10:
                nesne2.dac(0);
                nesne2.dyaz(soru1);
                nesne2.dkapat();
                nesne.dac(0);
                nesne.dyaz(cevap1);
                nesne.dkapat();
                break;
            default:
                break;
        }
                
                
        
    }//GEN-LAST:event_cevabıekleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scekleme4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scekleme4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scekleme4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scekleme4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scekleme4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cevabıekle;
    private javax.swing.JTextField cevap;
    private javax.swing.JButton geri;
    private javax.swing.JButton geri1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField soru;
    private javax.swing.JButton soruyuekle;
    // End of variables declaration//GEN-END:variables
}
